name: Mirror
description: Mirror components from a Figma file in a GitHub repository.
inputs:
  figma-file-key:
    description: Key that identifies the Figma file. (e.g., 2KN6A1IISYqTEnlbz3X8ks)
    required: true
  figma-file-name:
    description: Name of the Figma file. (e.g., branding)
    required: true
  figma-token:
    description: Figma access token.
    required: true
  format:
    description: Format in which to export components. (png, svg, jpg)
    required: true
    default: svg
runs:
  using: "composite"
  steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Delete Existing
      shell: bash
      run: rm -rf ./${{ inputs.figma-file-name }}/${{ inputs.format }}
    - name: Export Components
      uses: primer/figma-action@v1.0.0-alpha.3
      with:
        args: "format=${{ inputs.format }} outputDir=./${{ inputs.figma-file-name }}/"
      env:
        FIGMA_FILE_URL: "https://www.figma.com/file/${{ inputs.figma-file-key }}/${{ inputs.figma-file-name }}"
        FIGMA_TOKEN: ${{ inputs.figma-token }}
    - name: Change Permissions
      shell: bash
      run: |
        sudo chmod -R 777 ./${{ inputs.figma-file-name }}
        mv ./${{ inputs.figma-file-name }}/data.json ./${{ inputs.figma-file-name }}/${{ inputs.format }}/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      id: create-pull-request
      with:
        delete-branch: true
        branch: figma/${{ inputs.figma-file-name }}-${{ inputs.format }}
        commit-message: Mirror ${{ inputs.figma-file-name }}/${{ inputs.format }}
        title: Mirror `${{ inputs.figma-file-name }}/${{ inputs.format }}`
        body: Changes generated by [mirror](https://github.com/wager/design/actions/workflows/mirror.yaml).
        labels: enhancement
    - name: Auto-Merge Pull Request
        if: steps.create-pull-request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash
