name: mirror
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  branding:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Mirror PNG
        uses: ./.github/actions/mirror
        with:
          figma-file-key: 2KN6A1IISYqTEnlbz3X8ks
          figma-file-name: branding
          figma-token: ${{ secrets.FIGMA_TOKEN }}
          format: png
      - name: Mirror SVG
        uses: ./.github/actions/mirror
        with:
          figma-file-key: 2KN6A1IISYqTEnlbz3X8ks
          figma-file-name: branding
          figma-token: ${{ secrets.FIGMA_TOKEN }}
          format: svg
