name: mirror
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  mirror:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        figma-file-name: [branding, architecture]
        format: [png, svg, jpg]
        include:
          - figma-file-name: branding
            figma-file-key: 2KN6A1IISYqTEnlbz3X8ks
          - figma-file-name: architecture
            figma-file-key: cBAORqCYFhKdtHQcHYoMXH
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Mirror ${{ matrix.figma-file-name}}/${{ matrix.format }}
        uses: ./.github/actions/mirror
        with:
          figma-file-key: ${{ matrix.figma-file-key }}
          figma-file-name: ${{ matrix.figma-file-name }}
          figma-token: ${{ secrets.FIGMA_TOKEN }}
          format: ${{ matrix.format }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
